PostgreSQL:
  restart: always
  image: gotfix/postgresql:9.6.2-5
  ports:
    - "5432:5432"
  environment:
    - DEBUG=false

    - DB_USER=
    - DB_PASS=
    - DB_NAME=
    - DB_TEMPLATE=

    - DB_EXTENSION=

    - REPLICATION_MODE=
    - REPLICATION_USER=
    - REPLICATION_PASS=
    - REPLICATION_SSLMODE=
  volumes:
    - ./postgresql:/var/lib/postgresql
